Object Tracking CI Test

diff --git a/.github/workflows/CI_Testing.yml b/.github/workflows/CI_Testing.yml
--- a/.github/workflows/CI_Testing.yml
+++ b/.github/workflows/CI_Testing.yml
@@ -24,22 +24,22 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r Requirements.txt
-    
-    - name: Run Basketball Passing Simulation test
-      run: python Basketball_Passing_Simulation.py
 
-    - name: Check Basketball Passing Simulation log
-      run: |
-        if grep -q "succeeded" game_simulation_output.log; then
-          echo "Basketball Game Simulation test succeeded"
-        elif grep -q "failed" passing_simulation_output.log; then
-          echo "Basketball Game Simulation test failed"
-          exit 1
-        else
-          echo "Unable to determine test result"
-          exit 1
-        fi
-    
+    #- name: Run Basketball Passing Simulation test
+    #  run: python Basketball_Passing_Simulation.py
+
+    #- name: Check Basketball Passing Simulation log
+    #  run: |
+    #    if grep -q "succeeded" game_simulation_output.log; then
+    #      echo "Basketball Game Simulation test succeeded"
+    #    elif grep -q "failed" passing_simulation_output.log; then
+    #      echo "Basketball Game Simulation test failed"
+    #      exit 1
+    #    else
+    #      echo "Unable to determine test result"
+    #      exit 1
+    #    fi
+
     - name: Run Basketball Object Tracking test
       run: python Basketball_Object_Tracking.py
 
